package com.naappe.goldfieldlab;

import android.app.*;import android.os.*;import android.graphics.Color;import android.hardware.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.Locale;

public class MainActivity extends Activity implements SensorEventListener{
 SensorManager sm;Sensor mag;TextView total,axes,delta,status,result;float baseline=-1,peak=0,last=0;LinearLayout root;
 public void onCreate(Bundle b){super.onCreate(b);sm=(SensorManager)getSystemService(SENSOR_SERVICE);mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);build();}
 TextView t(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setGravity(Gravity.CENTER);v.setPadding(8,12,8,12);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(18);b.setMinHeight(64);return b;}
 void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,24,20,40);root.setBackgroundColor(Color.rgb(7,19,35));sv.addView(root);root.addView(t("🧲 Gold Field Lab",34));root.addView(t("Native magnetometer + gold density estimator",17));
  total=t("--.- µT",54);total.setTextColor(Color.rgb(57,209,232));root.addView(total);axes=t("X --.-   Y --.-   Z --.-",22);root.addView(axes);delta=t("Change from baseline: --.- µT",20);root.addView(delta);status=t(mag==null?"No magnetometer on this phone":"Sensor ready",18);root.addView(status);
  Button cal=btn("CALIBRATE BASELINE");cal.setOnClickListener(v->{if(last>0){baseline=last;peak=last;status.setText("Baseline calibrated");}});root.addView(cal);
  root.addView(t("Gold Density Test",28));root.addView(t("Use a scale. Enter weight in air and apparent weight while fully suspended in water. Do not let the item touch the cup.",16));
  EditText air=new EditText(this);air.setHint("Weight in air (g)");air.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);air.setTextColor(Color.WHITE);air.setHintTextColor(Color.LTGRAY);root.addView(air);
  EditText water=new EditText(this);water.setHint("Apparent weight in water (g)");water.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);water.setTextColor(Color.WHITE);water.setHintTextColor(Color.LTGRAY);root.addView(water);
  result=t("Density result will appear here",19);root.addView(result);Button calc=btn("CALCULATE GOLD DENSITY");calc.setOnClickListener(v->{try{double a=Double.parseDouble(air.getText().toString()),w=Double.parseDouble(water.getText().toString());if(a<=w||w<=0)throw new Exception();double d=a/(a-w);String band=d>=18.5?"consistent with very high-purity gold":d>=15?"may be a high-karat gold alloy":d>=12.5?"may be a lower-karat gold alloy":"not consistent with typical solid gold density";result.setText(String.format(Locale.US,"Specific gravity: %.2f\nResult: %s\nThis is an estimate, not proof. Hollow items, stones, trapped air and alloy composition affect the result.",d,band));}catch(Exception e){result.setText("Enter valid measurements. Weight in air must be greater than apparent weight in water.");}});root.addView(calc);
  root.addView(t("Important: the magnetometer cannot identify gold. A strong magnetic response usually means a magnet or ferromagnetic metal. Gold estimation here uses hydrostatic density: SG = air weight ÷ (air weight − water weight).",15));setContentView(sv);}
 protected void onResume(){super.onResume();if(mag!=null)sm.registerListener(this,mag,SensorManager.SENSOR_DELAY_GAME);}protected void onPause(){super.onPause();sm.unregisterListener(this);}public void onAccuracyChanged(Sensor s,int a){}
 public void onSensorChanged(SensorEvent e){float x=e.values[0],y=e.values[1],z=e.values[2],m=(float)Math.sqrt(x*x+y*y+z*z);last=m;peak=Math.max(peak,m);float d=baseline<0?0:Math.abs(m-baseline);total.setText(String.format(Locale.US,"%.1f µT",m));axes.setText(String.format(Locale.US,"X %.1f   Y %.1f   Z %.1f",x,y,z));delta.setText(String.format(Locale.US,"Change from baseline: %.1f µT",d));status.setText(m>2000?"Very strong field — move magnet away":m>500||d>300?"Strong magnetic field detected":d>40?"Strong magnetic change detected":"Live sensor active");}
}
